[project]
name = "ekyc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "boxmot>=11.0.6",
    "fastapi[standard]>=0.115.6",
    "pipreqs>=0.5.0",
    "ruff>=0.8.4",
    "ultralytics>=8.3.53",
]
